apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: myapp-backend:latest
          imagePullPolicy: Never # Forces k8s to use your local Docker image
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: DB_NAME
              value: "mydb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000